# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='extra',
        ),
        migrations.AddField(
            model_name='student',
            name='first_time',
            field=models.BooleanField(default=False),
        ),
    ]
